/**
 * Lists the contract changelog's version files for the build.
 *
 * Each contract version is its own file, src/changes/<version>.ts, so two
 * pull requests never edit a shared line. TypeScript and the Lambda
 * bundles need static imports, so before `tsc` this writes the gitignored
 * src/generated/:
 *
 *   changes.ts         imports every version file, newest first
 *   latest-version.ts  the highest version: CONTRACT_VERSION
 *
 * It refuses a file whose name is not a version. That the name agrees
 * with the entry, that no version repeats and that each version is a
 * semver successor of the one before are test/changelog.test.mjs's.
 *
 *   node scripts/changes-index.mjs
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VERSION_FILE = /^(\d+)\.(\d+)\.(\d+)\.ts$/;

/** A version's three numbers. */
export const parseVersion = (v) => {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(v);
  if (!m) throw new Error(`not a version: ${v}`);
  return [Number(m[1]), Number(m[2]), Number(m[3])];
};

/** Negative when a is older than b. */
export const compareVersions = (a, b) => {
  const [A, B] = [parseVersion(a), parseVersion(b)];
  for (let i = 0; i < 3; i++) if (A[i] !== B[i]) return A[i] - B[i];
  return 0;
};

/** The version after v for a patch, minor or major change. */
export const bumpVersion = (v, kind) => {
  const [major, minor, patch] = parseVersion(v);
  if (kind === "patch") return `${major}.${minor}.${patch + 1}`;
  if (kind === "minor") return `${major}.${minor + 1}.0`;
  if (kind === "major") return `${major + 1}.0.0`;
  throw new Error(`a bump is patch, minor or major, not ${kind}`);
};

/** The kind of bump that takes `from` to `to`, or null when none does. */
export const bumpKind = (from, to) =>
  ["patch", "minor", "major"].find((k) => bumpVersion(from, k) === to) ?? null;

/** The versions named by the files in a changes directory, newest first. */
export function versionsIn(names) {
  const versions = [];
  for (const name of names) {
    if (!name.endsWith(".ts")) continue;
    const m = VERSION_FILE.exec(name);
    if (!m)
      throw new Error(
        `src/changes/${name}: a version file is named <major>.<minor>.<patch>.ts`,
      );
    versions.push(name.slice(0, -3));
  }
  return versions.sort((a, b) => compareVersions(b, a));
}

const ident = (v) => `v${v.replaceAll(".", "_")}`;

const HEADER =
  "// Generated by packages/contracts/scripts/changes-index.mjs from\n" +
  "// src/changes/<version>.ts. Do not edit; gitignored.\n";

export function render(versions) {
  if (versions.length === 0) throw new Error("src/changes/ has no versions");
  const changes =
    HEADER +
    'import type { ChangelogEntry } from "../changelog-entry.js";\n' +
    versions
      .map((v) => `import ${ident(v)} from "../changes/${v}.js";\n`)
      .join("") +
    "\nexport const CHANGES: ChangelogEntry[] = [\n" +
    versions.map((v) => `  ${ident(v)},\n`).join("") +
    "];\n";
  const latest =
    HEADER + `export const LATEST_VERSION = ${JSON.stringify(versions[0])};\n`;
  return { "changes.ts": changes, "latest-version.ts": latest };
}

/** Writes src/generated/ for a package root; unchanged files are left alone. */
export function writeIndex(packageRoot) {
  const versions = versionsIn(
    readdirSync(path.join(packageRoot, "src/changes")),
  );
  const out = path.join(packageRoot, "src/generated");
  mkdirSync(out, { recursive: true });
  for (const [name, text] of Object.entries(render(versions))) {
    const file = path.join(out, name);
    if (!existsSync(file) || readFileSync(file, "utf8") !== text)
      writeFileSync(file, text);
  }
  return versions;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeIndex(path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."));
}
