import { randomBytes } from "node:crypto";
/**
 * Stack parameter discipline — Drop's pattern, must-ported (AGENTS.md).
 *
 * CloudFormation SILENTLY RESETS every parameter you omit on update-stack
 * to its template Default. Hardcoding a literal here is the same bug in a
 * different shape: the value you deploy stops tracking what an operator
 * set out-of-band. So parameters split into:
 *
 *  - REQUIRED: computed fresh every deploy (code keys). Always sent.
 *  - PRESERVED: set at create or by hand, then carried with
 *    UsePreviousValue on every update so a deploy can never clobber them
 *    (cert ARNs land when DNS/ACM exists; the cost threshold is Jamie's).
 */

export const REQUIRED_PARAMETERS = [
  "CodeBucket",
  "WebApiCodeKey",
  "McpCodeKey",
  "SchedulerCodeKey",
  "EmailRelayCodeKey",
  "MigrateCodeKey",
  "JobsCodeKey",
];

/**
 * SECRET: generated by the deploy on the parameter's FIRST deploy (create,
 * or the first update after the template gained it) and PRESERVED with
 * UsePreviousValue from then on. The value never lives in the repo, a
 * file, or a log; the template declares it NoEcho.
 */
export const SECRET_PARAMETERS = ["OriginSecret"];

export function generateSecret() {
  return randomBytes(32).toString("hex");
}

export const PRESERVED_PARAMETERS = [
  ...SECRET_PARAMETERS,
  "AppSecretName",
  "SiteCertificateArn",
  "MonthlyCostAlarmUsd",
  "SchedulerTickMinutes",
  // Replacement trigger: must never reset to default (see template).
  "DbSnapshotIdentifier",
  // Operational switch: a deploy must never silently turn the version
  // gate back off, or on.
  "CollectorMinEnforce",
];

/**
 * @param {Record<string,string>} required values for REQUIRED_PARAMETERS
 * @param {Record<string,string>} [initial] PRESERVED values (create only)
 */
export function buildParameters(
  required,
  initial = null,
  overrides = {},
  existingKeys = null,
) {
  for (const key of REQUIRED_PARAMETERS) {
    if (required[key] === undefined)
      throw new Error(`missing required parameter: ${key}`);
  }
  // A secret's first deploy: nothing to preserve yet, so mint one. At
  // create that is every secret; on update, only one the live stack does
  // not carry (existingKeys = the stack's current parameter keys).
  for (const key of SECRET_PARAMETERS) {
    if (overrides[key] !== undefined) continue;
    if (initial) {
      if (initial[key] === undefined)
        initial = { ...initial, [key]: generateSecret() };
    } else if (existingKeys && !existingKeys.includes(key)) {
      overrides = { ...overrides, [key]: generateSecret() };
    }
  }
  const params = REQUIRED_PARAMETERS.map((key) => ({
    ParameterKey: key,
    ParameterValue: required[key],
  }));
  for (const key of PRESERVED_PARAMETERS) {
    if (overrides[key] !== undefined) {
      // Explicit one-time set (e.g. a parameter's FIRST deploy, where
      // UsePreviousValue has nothing to point at). Preserved as usual
      // on every later deploy.
      params.push({
        ParameterKey: key,
        ParameterValue: String(overrides[key]),
      });
      continue;
    }
    if (initial) {
      if (initial[key] !== undefined) {
        params.push({
          ParameterKey: key,
          ParameterValue: String(initial[key]),
        });
      }
      // Omitted at create: the template Default applies, once, visibly.
    } else {
      params.push({ ParameterKey: key, UsePreviousValue: true });
    }
  }
  return params;
}
